/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Hero } from "./Hero";
export type { TestHero } from "./TestHero";
export * as factories from "./factories";
export { Hero__factory } from "./factories/Hero__factory";
export { TestHero__factory } from "./factories/TestHero__factory";
